### PR TITLE
docs(samples): Add samples for GameServerConfigs

### LINKED ISSUE #95: Add sample code for GameServerConfigs
This is a tracking bug for adding samples for missing gameServerConfigs.

### PR DESCRIPTION
**Pull request by pooneh-m**
Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [x] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/nodejs-game-servers/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [x] Ensure the tests and linter pass
- [x] Code coverage does not decrease (if any source code was changed)
- [x] Appropriate docs were updated (if necessary)

Fixes #95 🦕

### CODE REVIEW

**Comment by pooneh-m** [comment]
@JustinBeckwith could you please review?

**Comment by JustinBeckwith** [comment]
Caught up in meetings today, over to @bcoe

**Comment by pooneh-m** [comment]
@JustinBeckwith do you mind review this PR as well?

**Comment by pooneh-m** [comment]
Friendly ping!

**Review by JustinBeckwith — APPROVED** [review]

**Pull request merged**
